server:
  port: 8080
  servlet:
    context-path: /api/v1/seshat-page-service

spring:
  data:
    mongodb:
      uri: mongodb+srv://foodie:foodie@cluster0.t4mq9fc.mongodb.net/developer_iq_tracker?authSource=admin&replicaSet=atlas-bdifu0-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true

