server:
  port: 8080
  servlet:
    context-path: /api/v1/seshat-page-service

spring:
  data:
    mongodb:
      uri: mongodb+srv://janith20230370:RBD6zVuBwOjnmHR8@seshat.nrn4uu0.mongodb.net/seshat-KidLuma

