name: seshat-page-service CI CD flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: seshat
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: seshat-page-service
  IMAGE: seshat-page-service
  TAG: prod

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploys
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven With Test
        run: mvn clean install -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker in GKE
        run: gcloud --quiet auth configure-docker

      - name: Get SI Credentials GKE
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Docker Image GCR
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

      - name: Install Gcloud Component
        run: |-
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy Image to GKE cluster
        run: |-
          kubectl apply -f service.yaml
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment $DEPLOYMENT_NAME
          kubectl get services -o wide